version: '3.3'
services:
  meshify-client:
    container_name: meshify-client
    image: meshify-client
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    environment:
      - USERID
      - GROUPID
      - MESHIFY_HOST
      - MESHIFY_HOST_ID
      - MESHIFY_API_KEY
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "30000:30000/udp"

