version: '3.3'
services:
  meshify-client-build:
    container_name: meshify-client-build
    image: meshify-client-build
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    volumes:
      - .:/docker
    environment:
      - USERID
      - GROUPID
    secrets:
      - user_ssh_key
secrets:

  user_ssh_key:

    file: ~/.ssh/id_rsa
