version: '3.3'
services:
  meshify-service-host:
    container_name: meshify-service-host
    image: meshify-client
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    volumes:
      - /var/meshify/test:/etc/meshify
    environment:
      - USERID
      - GROUPID
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "30000:30000/udp"

